# Generated by Django 4.2 on 2023-04-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_delivery_crew',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
    ]
